### ISSUE TITLE
Bizarre copy of ARRAY in list assignment

### ISSUE THREAD

**Issue by FGasper** [pjcj/Devel--Cover#125]
```
use strict;
use warnings;

use Test::More tests => 1;

use Fcntl;

{
    my $temp_file = '/tmp/foo';

    unlink $temp_file;

    for ( 1 .. 3 ) {
        my $t_fh;

        #NOTE: Uncomment these, and the problem goes away!
        #use IO::Handle;
        #$t_fh = IO::Handle->new();

        sysopen_wrap(
            $t_fh,
            $temp_file,
            O_WRONLY | O_TRUNC | O_CREAT,
        );

    }

    unlink $temp_file;

    ok 1;
}

sub sysopen_wrap {
    my ( $fh_r, $file, $mode ) = ( \shift, @_ );

    return sysopen( $$fh_r, $file, $mode, 0666 );
}
```

> perl5.14 "-MDevel::Cover=-coverage,statement" devel_cover_err.t 
1..1
Devel::Cover 1.18: Collecting coverage data for statement.
Selecting packages matching:
Ignoring packages matching:
    /Devel/Cover[./]
Ignoring packages in:
    /opt/local/lib/perl5/site_perl/5.14.4/darwin-thread-multi-2level
    /opt/local/lib/perl5/site_perl/5.14.4
    /opt/local/lib/perl5/5.14.4/darwin-thread-multi-2level
    /opt/local/lib/perl5/5.14.4
    /opt/local/lib/perl5/site_perl
    /opt/local/lib/perl5/vendor_perl
ok 1
Devel::Cover: Oops, it looks like something went wrong writing the coverage.
              It's possible that more bad things may happen but we'll try to
              carry on anyway as if nothing happened.  At a minimum you'll
              probably find that you are missing coverage.  If you're
              interested, the problem was:

Bizarre copy of ARRAY in list assignment at /opt/local/lib/perl5/5.14.4/darwin-thread-multi-2level/B.pm line 258.

---------------

NOTE: I have also seen this generate:

Argument "*main::_GEN_2" isn't numeric in addition (+)

… but right now I can’t reproduce that as readily.

**Comment by FGasper** [comment]
Note that, if the open() operates on $_[0] directly, then there’s no error. The problem seems to be from creating a reference to $_[0] and using that reference (even dereferenced!) in the open().

**Comment by bk2204** [comment]
This may fail differently if run multiple times. It also fails for me with Devel::Cover 1.18 and Debian's Perl 5.20.2.

**Comment by FGasper** [comment]
An even simpler version:

```
use Test::More tests => 1;

my $temp_file = '/tmp/foo';

unlink $temp_file;

for ( 1 .. 3 ) {
    my $t_fh;

    #NOTE: Uncomment these, and the problem goes away!
    #use IO::Handle;
    #$t_fh = IO::Handle->new();

    open( ${ \$t_fh }, '>', $temp_file );

}

unlink $temp_file;

ok 1;
```

**Comment by toddr** [comment]
This also breaks in the same way:

sub open_wrap {
   my ($fh_ref) = (\shift)
    return open( $$fh_ref, '>', $_[1] );
}

But this does not break:

sub open_wrap {
    return open( $_[0], '>', $_[1] );
}

**Comment by pjcj** [comment]
Thanks for finding and reporting this.  On the surface it looks like a problem with B::Deparse, or at least with the way in which Devel::Cover is using it.  But some of the other clues point in different directions.  I'll try to narrow it down further.

**Comment by toddr** [comment]
FYI we've seen errors from B/Deparse.pm, depending on the size of the test file / planetary alignment, etc. so that does happen some times.

**Comment by FGasper** [comment]
Simplest yet:

```
use Test::More tests => 1;

for ( 1 .. 3 ) {
    my $t_fh;
    open( ${ \$t_fh }, '>', '/dev/null' );
}

ok 1;
```

… and here’s what’s interesting here: The first time this runs, it runs fine. The SECOND time, it blows up:

```
Felipe@Felipes-Mac-Pro ~/code
> perl5.14 '-MDevel::Cover=-coverage,statement' devel_cover_err.t 
1..1
Devel::Cover 1.18: Collecting coverage data for statement.
Selecting packages matching:
Ignoring packages matching:
    /Devel/Cover[./]
Ignoring packages in:
    /opt/local/lib/perl5/site_perl/5.14.4/darwin-thread-multi-2level
    /opt/local/lib/perl5/site_perl/5.14.4
    /opt/local/lib/perl5/5.14.4/darwin-thread-multi-2level
    /opt/local/lib/perl5/5.14.4
    /opt/local/lib/perl5/site_perl
    /opt/local/lib/perl5/vendor_perl
ok 1
Devel::Cover: Writing coverage database to /Users/Felipe/code/cover_db/runs/1431969556.33084.23696
--------------------------------------------------------------- ------ ------
File                                                              stmt  total
--------------------------------------------------------------- ------ ------
devel_cover_err.t                                                100.0  100.0
Total                                                            100.0  100.0
--------------------------------------------------------------- ------ ------



OK
Felipe@Felipes-Mac-Pro ~/code
> perl5.14 '-MDevel::Cover=-coverage,statement' devel_cover_err.t 
1..1
Devel::Cover 1.18: Collecting coverage data for statement.
Selecting packages matching:
Ignoring packages matching:
    /Devel/Cover[./]
Ignoring packages in:
    /opt/local/lib/perl5/site_perl/5.14.4/darwin-thread-multi-2level
    /opt/local/lib/perl5/site_perl/5.14.4
    /opt/local/lib/perl5/5.14.4/darwin-thread-multi-2level
    /opt/local/lib/perl5/5.14.4
    /opt/local/lib/perl5/site_perl
    /opt/local/lib/perl5/vendor_perl
ok 1
Devel::Cover: Oops, it looks like something went wrong writing the coverage.
              It's possible that more bad things may happen but we'll try to
              carry on anyway as if nothing happened.  At a minimum you'll
              probably find that you are missing coverage.  If you're
              interested, the problem was:

Bizarre copy of HASH in list assignment at /opt/local/lib/perl5/5.14.4/darwin-thread-multi-2level/B.pm line 258.
```

**Comment by rurban** [comment]
This is an old B core bug, fixed later.

You may not walk the symstash with each %$symref, as perl hash iterators are not safe to use when the hash is being changed. More info at https://code.google.com/p/perl-compiler/issues/detail?id=307 and http://perl5.git.perl.org/perl.git/commit/5cc8528c900964306cba9b53c6eaa27af540eaea?f=ext/B/B.pm

I fixed it in the compiler to be backwards safe, but for Devel::Cover I would suggest to ignore it.

**Comment by toddr** [comment]
In at least one case, I know we have patched B.pm like it's patched here. The problem persists. 

http://perl5.git.perl.org/perl.git/blobdiff/c31ee3bbc31a4f8c5b4850ce38fb8c353dca688f..5cc8528c900964306cba9b53c6eaa27af540eaea:/ext/B/B.pm

@rurban are you saying the bug is the lack of patching to B.pm or how other code is expecting B.pm to misbehave?

**Comment by FGasper** [comment]
I’ve found before that simply skipping GEN symbols fixes the issue:

```
  sub walksymtable {
      my ($symref, $method, $recurse, $prefix) = @_;
      my $sym;
      my $ref;
      my $fullname;
      no strict 'refs';
      $prefix = '' unless defined $prefix;
      foreach my $sym ( sort keys %$symref ) {
+ next if $sym =~ m<\A_GEN_[0-9]+\z>;
          $ref= $symref->{$sym};
```

**Comment by rurban** [comment]
toddr: There are 2 known core bugs (they call it limitations) with hash iterators.
The first one is striking here: iterating over rehashed hashes is broken.
The 2nd one is scoped iterators are not supported, the eiter and riter HvAUX pointers need to be moved from the hash to the op, so that ending loops will re-instate the old iterator position.

FGasper's fix is the current best workaround which we are also using in a similar form the compiler. Empty stashes in _GEN syms will cause this symptom.
I'm just starting to fix the real bugs/limitations internally.

```
# Fixes bug #307: use foreach, not each
# each is not safe to use (at all). walksymtable is called recursively which might add
# symbols to the stash, which might cause re-ordered rehashes, which will fool the hash
# iterator, leading to missing symbols in the binary.
# Old perl5 bug: The iterator should really be stored in the op, not the hash.
sub walksymtable {
  my ($symref, $method, $recurse, $prefix) = @_;
  my ($sym, $ref, $fullname);
  $prefix = '' unless defined $prefix;
  foreach my $sym ( sort keys %$symref ) {
    no strict 'refs';
    $ref = $symref->{$sym};
    $fullname = "*main::".$prefix.$sym;
    if ($sym =~ /::$/) {
      $sym = $prefix . $sym;
      if (svref_2object(\*$sym)->NAME ne "main::" && $sym ne "<none>::" && &$recurse($sym)) {
        walksymtable(\%$fullname, $method, $recurse, $sym);
      }
    } else {
      svref_2object(\*$fullname)->$method();
    }
  }
}
```

**Comment by pjcj** [comment]
Have I understood correctly that I can ignore this in Devel::Cover as it is a bug in B which is already patched in the most recent release?

That would be great as I am having difficulty reproducing the problem anyway.

**Comment by rurban** [comment]
pjcj: There are several bugs, only one fixed.

walksymtable each was "fixed" in 5.16. In detail, each was not fixed and probably will never be fixed, but a workaround is used.

Felipe found the _GEN sym problem which is not yet fixed, and our current workaround is not yet good enough.
One idea is that is caused by an `\undef`, the other an empty stash caused by Symbol. I haven't had time to look at it.

**Comment by toddr** [comment]
Do be clear, some action needs taking since Devel Cover is corrupting at the moment and the problem in B *if there is one) is not fixed or identified.

**Comment by rurban** [comment]
Yes, but this is still a core bug. B::walksymtable is maintained at p5p.

**Comment by bk2204** [comment]
If the B issue was fixed in 5.16, then there is still a bug in Devel::Cover. As I stated above, I can reproduce this with Debian's 5.20.2, which would have that issue fixed.

**Comment by rurban** [comment]
@bk2204 As I said there are multiple issues in B. The sort each was fixed in 5.16, the _GEN_ is not yet fixed. All these are B issues for which we have our two internal tickets.

Devel::Cover has no issue AFAIK, but should patch B:: walksymtable for older versions, same as we do.

**Comment by rurban** [comment]
Patching B::walksymtable is only needed <= 5.20, 5.22 had this now fixed.
You will only see it when walking B itself, which is usually excluded in the testsuite.

See my testcase in https://github.com/rurban/Devel--Cover/commits/gh125-gensym

**Comment by pjcj** [comment]
I think this was mostly fixed before, but I've just been through all the examples shown in the comments and ensured everything passes on `main` so I'm going to close this now in conjunction with #276.  Thanks to everyone who helped in nailing it down!
